controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
constat_location:
    path: '/constat/location'
    controller: App\Controller\ConstatController::getLocation