#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# app_user_delete:
#     path: '/delete/{id}'
#     controller: App\Controller\UserController::delete
#     methods: ['DELETE']




# suppC:
#     path: '/removeClientt/{id}'
#     controller: App\Controller\ClienttController::suppC
#     requirements:
#         id: '[0-9]+'
#     methods: ['DELETE']


# modifClientt:
#     path: '/modifClientt/{id}'
#     controller: App\Controller\ClienttController::modifClientt  
#     requirements:
#         id: '[^\s/]+'

# createUser:
#     path: /create
#     controller: App\Controller\RegistrationController::createUser
#     methods: ['POST']

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
view_contrats:
    path: '/voiture/{id}/contrats'
    controller: App\Controller\ContratController::viewContrats
    


contrat_delete:
    path: '/contrat/{id}'
    controller: App\Controller\ContratController::delete
    requirements:
        id: '\d+'

voiture_edit:
    path: '/voiture/{id}/edit'
    controller: App\Controller\VoitureController::edit
    methods: ['GET', 'POST']
    requirements:
        id: '\d+'

        

        